[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production" 