[build]
builder = "DOCKERFILE"
buildCommand = "docker build -t spacechat-live ."

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production" 